# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: jekit-halo
spec:
  enabled: true
  requires: ">=2.26.0"
  author:
    name: heyManNice
    website: https://github.com/heyManNice
  logo: favicon.ico
  homepage: https://github.com/heyManNice/jekit-sdk#readme
  repo: https://github.com/heyManNice/jekit-sdk
  issues: https://github.com/heyManNice/jekit-sdk/issues
  displayName: "Jekit 统计"
  description: "无需部署额外统计服务，为 Halo 提供访问统计、文章阅读量和页脚指标。"
  settingName: jekit-settings
  configMapName: jekit-config
  license:
    - name: "MIT"
      url: "https://github.com/heyManNice/jekit-sdk/blob/main/integrations/halo/LICENSE"
