# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: jekit-halo
spec:
  enabled: true
  requires: ">=2.26.0"
  author:
    name: heyManNice
    website: https://github.com/heyManNice
  logo: favicon.ico
  homepage: https://jekit.cn
  repo: https://github.com/heyManNice/jekit-sdk
  issues: https://github.com/heyManNice/jekit-sdk/issues
  displayName: "Jekit 统计"
  description: "安装即用，无需自建统计服务。为 Halo 提供访问趋势、来源分析与网站性能指标，并支持文章阅读量和页脚统计。"
  settingName: jekit-settings
  configMapName: jekit-config
  license:
    - name: "MIT"
      url: "https://github.com/heyManNice/jekit-sdk/blob/main/integrations/halo/LICENSE"
