plugins {
    id 'base'
    id "com.github.node-gradle.node" version "7.1.0"
}

group 'cn.jekit.jekit.greeter'

tasks.register('pnpmBuild', PnpmTask) {
    group = 'build'
    description = 'Build the Jekit greeter for Halo using pnpm'
    args = ['build']
    dependsOn tasks.named('pnpmInstall')
    inputs.dir(layout.projectDirectory.dir('src'))
    inputs.files(fileTree(
        dir: layout.projectDirectory,
        includes: ['*.ts', '*.json']))
    outputs.dir(layout.buildDirectory.dir('dist'))
}

tasks.named('assemble') {
    dependsOn tasks.named('pnpmBuild')
}
